/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecettesRouteImport } from './routes/recettes'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CaisseRouteImport } from './routes/caisse'
import { Route as BackofficeRouteImport } from './routes/backoffice'
import { Route as IndexRouteImport } from './routes/index'

const RecettesRoute = RecettesRouteImport.update({
  id: '/recettes',
  path: '/recettes',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CaisseRoute = CaisseRouteImport.update({
  id: '/caisse',
  path: '/caisse',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRoute = BackofficeRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/caisse': typeof CaisseRoute
  '/catalogue': typeof CatalogueRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/recettes': typeof RecettesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/caisse': typeof CaisseRoute
  '/catalogue': typeof CatalogueRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/recettes': typeof RecettesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRoute
  '/caisse': typeof CaisseRoute
  '/catalogue': typeof CatalogueRoute
  '/login': typeof LoginRoute
  '/panier': typeof PanierRoute
  '/recettes': typeof RecettesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/caisse'
    | '/catalogue'
    | '/login'
    | '/panier'
    | '/recettes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backoffice'
    | '/caisse'
    | '/catalogue'
    | '/login'
    | '/panier'
    | '/recettes'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/caisse'
    | '/catalogue'
    | '/login'
    | '/panier'
    | '/recettes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRoute: typeof BackofficeRoute
  CaisseRoute: typeof CaisseRoute
  CatalogueRoute: typeof CatalogueRoute
  LoginRoute: typeof LoginRoute
  PanierRoute: typeof PanierRoute
  RecettesRoute: typeof RecettesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recettes': {
      id: '/recettes'
      path: '/recettes'
      fullPath: '/recettes'
      preLoaderRoute: typeof RecettesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caisse': {
      id: '/caisse'
      path: '/caisse'
      fullPath: '/caisse'
      preLoaderRoute: typeof CaisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRoute: BackofficeRoute,
  CaisseRoute: CaisseRoute,
  CatalogueRoute: CatalogueRoute,
  LoginRoute: LoginRoute,
  PanierRoute: PanierRoute,
  RecettesRoute: RecettesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
